### ISSUE TITLE
Support more than 4 attachments

### ISSUE THREAD

**Issue by ledlamp** [TheEssem/mastodon#13]
### Pitch

Allow more than four attachments on a post

### Motivation

Since this fork adds reactions, and all the other platforms that have reactions also support more than 4 attachments, I think this fork ought to support it as well.

I like the design of mastodon but don't like it's limitations, so it's nice that there are forks like glitch-soc and chuckya to restore useful functionality and feature parity, but this one thing was a deal-breaker for me.

I think it is an especially important feature because people on pleroma and misskey frequently attach more than 4 files, and mastodon users have no clue about it.

**Comment by TheEssem** [comment]
This is now controllable via the `MAX_MEDIA_ATTACHMENTS` and `MAX_REMOTE_MEDIA_ATTACHMENTS` environment variables.
