### ISSUE TITLE
Setting visible reaction count to 0 does not hide them

### ISSUE THREAD

**Issue by Makuramancer** [TheEssem/mastodon#19]
### Steps to reproduce the problem

1. Set number of visible emoji reactions to 0 in user preferences

### Expected behaviour

Reactions on posts are not visible at all

### Actual behaviour

The setting is ignored, and reactions are displayed as if there wasn't a limitation set

### Detailed description

![Screenshot from 2024-06-16 18-47-31](https://github.com/TheEssem/mastodon/assets/73392151/ddbcba33-88b3-43a2-a542-4b5614b19dc5)
![Screenshot from 2024-06-16 18-49-51](https://github.com/TheEssem/mastodon/assets/73392151/2f3e81b9-3735-4eaf-b05b-36243af8579d)

### Mastodon instance

wetdry.world

### Mastodon version

v4.3.0-alpha.4+chuckya

### Browser name and version

Firefox 127

### Operating system

Fedora 40

**Comment by Makuramancer** [comment]
Setting reactions to even a very small number like 1 does not seem to make a difference

**Comment by TheEssem** [comment]
The setting looks to be meant for the in-timeline status view, where a smaller amount is required; I've gone ahead and made it so that it hides it completely on both views when set to 0 with 5668926ffa465ae09d17d2506bd8eb68100dd9c1.
