### ISSUE TITLE
Unable to start any service after upgrade - "ruby_executable_hooks": No such file or directory.

### ISSUE THREAD

**Issue by s626ch** [TheEssem/mastodon#26]
### Steps to reproduce the problem

I donʻt know if this is a fault of Chuckya or upstream Mastodon, but after an upgrade, none of my services will start.
Iʻve tried upgraded Ruby to 3.3.5 using both rbenv and rvm, tried `bundle exec rails yarn:install assets:clobber assets:precompile`, tried following the [upgrade instructions](https://docs.joinmastodon.org/admin/upgrading/), tried `gem install executable-hooks`, absolutely nothing is working.

### Expected behaviour

A clean upgrade?

### Actual behaviour

Inability to start services.

### Detailed description

The biggest piece of info I can really give is that my instance was a few months out of date (mostly because every time I do upgrade, I end up with big headaches like this that cause 12+ hours of downtime)

I run a small instance off of a Raspberry Pi 4b (8gb RAM), aarch64.

If I need to move this issue to upstream Mastodon, I gladly will.

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [aarch64-linux]
- Node.js version: v18.17.1

**Comment by s626ch** [comment]
Going to addendum that thereʻs likely commands I missed between each upgrade, if I can find them Iʻll attempt that.

**Comment by TheEssem** [comment]
What errors do the services output when attempting to start them?

**Comment by s626ch** [comment]
```
root@imhaater-pi:/home/mastodon/live# systemctl restart mastodon-*
root@imhaater-pi:/home/mastodon/live# journalctl -fu mastodon-sidekiq
-- Journal begins at Sun 2024-07-14 17:45:01 EDT. --
Oct 09 05:32:01 imhaater-pi systemd[1]: mastodon-sidekiq.service: Consumed 1.639s CPU time.
Oct 09 05:32:01 imhaater-pi systemd[1]: Started mastodon-sidekiq.
Oct 09 05:32:03 imhaater-pi bundle[3872794]: /usr/bin/env: ‘ruby_executable_hooks’: No such file or directory
Oct 09 05:32:03 imhaater-pi systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=127/n/a
Oct 09 05:32:03 imhaater-pi systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
Oct 09 05:32:03 imhaater-pi systemd[1]: mastodon-sidekiq.service: Consumed 1.609s CPU time.
Oct 09 05:32:03 imhaater-pi systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 2.
Oct 09 05:32:03 imhaater-pi systemd[1]: Stopped mastodon-sidekiq.
Oct 09 05:32:03 imhaater-pi systemd[1]: mastodon-sidekiq.service: Consumed 1.609s CPU time.
Oct 09 05:32:04 imhaater-pi systemd[1]: Started mastodon-sidekiq.
Oct 09 05:32:05 imhaater-pi bundle[3872834]: /usr/bin/env: ‘ruby_executable_hooks’: No such file or directory
Oct 09 05:32:05 imhaater-pi systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=127/n/a
Oct 09 05:32:05 imhaater-pi systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
Oct 09 05:32:05 imhaater-pi systemd[1]: mastodon-sidekiq.service: Consumed 1.413s CPU time.
Oct 09 05:32:05 imhaater-pi systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 3.
Oct 09 05:32:05 imhaater-pi systemd[1]: Stopped mastodon-sidekiq.
Oct 09 05:32:05 imhaater-pi systemd[1]: mastodon-sidekiq.service: Consumed 1.413s CPU time.
Oct 09 05:32:05 imhaater-pi systemd[1]: Started mastodon-sidekiq.
```
same thing as in issue title

**Comment by TheEssem** [comment]
Mastodon's docs recommend using rbenv with the ruby-build plugin; try that instead of rvm and see if it works.

**Comment by s626ch** [comment]
Iʻll try reinstalling 3.3.5 with rbenv, ruby-build is already present.

**Comment by s626ch** [comment]
![UrIsEr1EJt](https://github.com/user-attachments/assets/1afc9353-0766-4b5d-bb87-46ce141867c3)
well, getting...somewhere
this is located within `/usr/local/bin/`

**Comment by s626ch** [comment]
![aU8RoN0E9v](https://github.com/user-attachments/assets/e78740d8-12c2-4857-96c9-7fef855967e3)
i have absolutely no fucking idea what itʻs trying to do

**Comment by s626ch** [comment]
friend of mine helped me migrate to a dockerized instance, everything prior has been purged, sorry if anyone else has this issue. my solution was to start anew and carry the db along

**Comment by s626ch** [comment]
friend of mine helped me migrate to a dockerized instance, everything prior has been purged, sorry if anyone else has this issue. my solution was to start anew and carry the db along
