### ISSUE TITLE
Network Error when pinning the Bubble servers feed on deck view

### ISSUE THREAD

**Issue by CivilizedGuide** [TheEssem/mastodon#27]
### Steps to reproduce the problem

1. Use deck view
2. Select local timeline
3. From the tabs select Bubble servers
4. Pin the Bubble server feed
...

### Expected behaviour

Bubble feed is pinned on the deckview

### Actual behaviour

A network error appears insted of the feed

### Mastodon instance

wetdry.world

### Mastodon version

v4.4.0-alpha.1+chuckya

### Browser name and version

Librewolf 132.0.2-1, Ungoogled-Chromium 131.0.6778.85

### Operating system

Void Linux; Linux Kernel 6.6.63

### Technical details

These seem to be related
```
The resource at “https://wetdry.world/packs/js/flavours/glitch/async/home_timeline-removedforprivacy.chunk.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. (https://wetdry.world/deck/getting-started)
The resource at “https://wetdry.world/packs/js/flavours/glitch/async/notifications-removedforprivacy.chunk.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
```

**Comment by TheEssem** [comment]
Fixed in 38de889314d246913bb9520c5911248ac06b3ce8.
