### ISSUE TITLE
"Bubble servers" feed pulls from "All servers" instead

### ISSUE THREAD

**Issue by eblu3** [TheEssem/mastodon#28]
### Steps to reproduce the problem

1. Open "Live feeds" tab
2. Click on "Bubble servers"

### Expected behaviour

Only posts from servers that were manually curated by instance staff should appear.

### Actual behaviour

Posts from all servers appear instead.

### Mastodon instance

wetdry.world

### Mastodon version

v4.4.0-alpha.1+chuckya

### Technical details

Previous discussion indicates that this bug varies from user to user and appears to work when you're logged out, as evidenced by opening the API endpoint (e.g. https://wetdry.world/api/v1/timelines/public?bubble=true&only_media=false) in a private window. This might indicate a configuration/database error? It's worth investigating.

**Comment by neatchee** [comment]
A clue: When this issue occurs, streaming inserts still appear only for servers in the bubble. The improper population of the feed appears to only  happen at page load

**Comment by TheEssem** [comment]
Quick question, do either of you have any account domain blocks or locale filters applied?

**Comment by TheEssem** [comment]
I think I just figured out the cause of the issue; the scopes for posts in the bubble and posts from non-account-blocked servers seem to conflict with each other, causing the latter to be applied instead.

Attempting to figure out how to resolve this.
