### ISSUE TITLE
Mimemagic v0.3.2 dependency yanked

### ISSUE THREAD

**Issue by damorphh** [TheEssem/mastodon#30]
### Steps to reproduce the problem

1. Follow install instructions for the first time
2. Run `bundle install -j$(getconf _NPROCESSORS_ONLN)`
3.  Outputs:
```
Fetching gem metadata from https://rubygems.org/..........
Your bundle is locked to mimemagic (0.3.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.2) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.2) that hasn't been removed in
order to install.
```
...

### Expected behaviour

Dependency should be updated, should output list of dependencies and then: 
```
Bundle complete! 80 Gemfile dependencies, 511 gems now installed. Gems in the groups development and test were not installed. Use `bundle info [gemname]` to see where a bundled gem is installed.
```

### Actual behaviour

It is trying to download an unavailable version of mimemagic, which paperclip (another dependency) depends on.

### Detailed description

I have never used Ruby before, so my apologies if I have done this wrong, but I fixed this by leaving deployment mode, editing the Gemfile to use paperclip 6.1 instead of 5.1, running `bundle update`, running `bundle install`, and then running `bundle install -j$(getconf _NPROCESSORS_ONLN)` like the docs say to.

However, if you do not leave deployment mode it outputs a message that may be confusing to some first-time Ruby users such as myself, which can be fixed by the Gemfile and Gemfile.lock matching in git I believe.

I tested this on upstream vanilla Mastodon (albeit by accident lol, I forgot to replace the git URL when copy-pasting from the docs) and did not have this issue, so I believe it is just that Chukya has to update their Gemfile in their git, but as I said earlier I'm a first-time Ruby user so I could be wrong.

Thanks in advance,
Kali

### Mastodon instance

anarchist.au (not running currently)

### Mastodon version

Not installed as of writing

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.3.5): `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
- Node.js version: (from `node --version`, eg. v20.18.0): `v20.18.1`

**Comment by damorphh** [comment]
After continuing to try and install Chukya I think I may be doing something wrong. I'll leave this open in case I'm not, but I'm going to try running with the pre-built docker image instead to minimise the damage of my inexperience lol, so I won't be here to keep running different things on my environment.

**Comment by TheEssem** [comment]
The reported Ruby version (2.4.1) is very old; Mastodon requires version 3.2 or newer. Additionally, `mimemagic` is not present in the current Gemfile.lock and `paperclip` was replaced with `kt-paperclip` quite a few years ago, so I suspect that something went wrong and you were somehow trying to build a very old version of Mastodon.

Closing as this seems to be unrelated to the software itself, but to how it was obtained. I'd suggest checking `git log` and seeing what the top commit is.

**Comment by damorphh** [comment]
Thanks for helping. I wonder why the old version of Ruby downloaded.
