### ISSUE TITLE
mentions have very low contrast on the high contrast theme

### ISSUE THREAD

**Issue by BenLubar** [TheEssem/mastodon#31]
### Steps to reproduce the problem

1. Set "flavor" to "high contrast"
2. Look at a post that contains a mention.

### Expected behaviour

The mention should be a significantly different color than the text of the post

### Actual behaviour

It isn't

### Detailed description

![image](https://github.com/user-attachments/assets/e63a8655-a67f-43d4-b1b3-aab776b11316)

This does not occur in upstream glitch-soc.

### Mastodon instance

mastodon.lubar.me

### Mastodon version

v4.4.0-nightly.2024-12-15+chuckya

### Browser name and version

Firefox 128.5.0esr

### Operating system

Debian trixie

**Comment by TheEssem** [comment]
I assume you have high-contrast enabled instance-wide? I just checked your instance and it appears that it's showing just fine:
![image](https://github.com/user-attachments/assets/a1fc5260-4299-4705-bf24-8b8ad8650b88)
Have you double-checked that your account skin is set to high-contrast? Is this on the regular view or deck view?

**Comment by BenLubar** [comment]
![Screenshot_20241216_101737](https://github.com/user-attachments/assets/c068135c-7a20-40a3-901a-a0a4c64a1574)
Weird, I clicked "save" on this page without changing anything and now it's showing what you see on the deck view.
